version: 2

jobs:
  build:
    working_directory: /home/reaction

    docker:
      - image: node:8

    environment:
      - DOCKER_VERSION: 17.05.0-ce
      - DOCKER_COMPOSE_VERSION: 1.15.0
      - METEOR_ALLOW_SUPERUSER: true
      - TOOL_NODE_FLAGS: "--max-old-space-size=4096"

    steps:
      - setup_remote_docker
      - checkout

      # install OS dependencies
      - restore_cache:
          name: Restoring Meteor cache
          key: meteor

      - run: .circleci/install.sh

      - save_cache:
          name: Saving Meteor to cache
          key: meteor
          paths:
            - ~/.meteor

      # install app dependencies

      - run: meteor npm install

      # run tests
      - restore_cache:
          name: Restoring Meteor dev_bundle cache
          key: dev_bundle

      # run reaction tests
      - run: .circleci/tests.sh

      - save_cache:
          name: Saving Meteor dev_bundle to cache
          key: dev_bundle
          paths:
            - /home/reaction/.meteor/local

      - run:
          command: .reaction/jsdoc/build.sh
          no_output_timeout: 2m

# Courivine and LeahLovise
      - deploy:
          name: Deploy to rancher if tests pass and branch is courivine
          command: |
            if [ "${CIRCLE_BRANCH}" == "courivine" ]; then
              echo "Building courivine"
              bash .courivine/build.sh
              echo "Deploying courivine"
              bash .courivine/deploy.sh
            elif [ "${CIRCLE_BRANCH}" == "leahlovise" ]; then
              echo "Building leahlovise"
              bash .leahlovise/build.sh
              echo "Deploying leahlovise"
              bash .leahlovise/deploy.sh
            else
              echo "Not courivine or leahlovise branch so not deploying"
            fi
